import type { FileNode } from '@shared/types'

export const DEMO_ROOT_NODE: FileNode = {
  id: 'root-c',
  name: 'Local Disk (C:)',
  path: 'C:\\',
  size: 136200000000, // ~126.84 GB
  type: 'directory',
  category: 'other',
  children: [
    // 1. Library Container (Top Left)
    {
      id: 'dir-library',
      name: 'Library',
      path: 'C:\\Library',
      size: 48500000000,
      type: 'directory',
      category: 'system',
      children: [
        {
          id: 'dir-containers',
          name: 'Containers',
          path: 'C:\\Library\\Containers',
          size: 24500000000,
          type: 'directory',
          category: 'cache',
          children: [
            {
              id: 'dir-windows-system-analysis',
              name: 'Windows.System.Analysis Data',
              path: 'C:\\Library\\Containers\\Windows.System.Analysis Data',
              size: 11850000000,
              type: 'directory',
              category: 'cache',
              children: [
                {
                  id: 'file-lib-caches',
                  name: 'Library Caches',
                  path: 'C:\\Library\\Containers\\Windows.System.Analysis Data\\Caches',
                  size: 11850000000,
                  type: 'file',
                  category: 'cache',
                },
              ],
            },
            {
              id: 'dir-unzip-any-file',
              name: 'com.Ababe.UnzipAnyFile Data',
              path: 'C:\\Library\\Containers\\com.Ababe.UnzipAnyFile Data',
              size: 9110000000,
              type: 'directory',
              category: 'cache',
              children: [
                {
                  id: 'file-app-support',
                  name: 'Library Application Support',
                  path: 'C:\\Library\\Containers\\com.Ababe.UnzipAnyFile Data\\Application Support',
                  size: 9110000000,
                  type: 'file',
                  category: 'system',
                },
              ],
            },
            {
              id: 'dir-caches-chrome',
              name: 'Caches Google Chrome',
              path: 'C:\\Library\\Containers\\Google Chrome',
              size: 3540000000,
              type: 'directory',
              category: 'cache',
              children: [
                {
                  id: 'file-prof-5',
                  name: 'Profile 5 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 5',
                  size: 889090000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-8',
                  name: 'Profile 8 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 8',
                  size: 836760000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-10',
                  name: 'Profile 10 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 10',
                  size: 793660000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-1',
                  name: 'Profile 1 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 1',
                  size: 420000000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-11',
                  name: 'Profile 11 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 11',
                  size: 320000000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-code-cache',
                  name: 'Code Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Code Cache',
                  size: 280490000,
                  type: 'file',
                  category: 'code',
                },
              ],
            },
            {
              id: 'dir-brave',
              name: 'BraveSoftware Brave-Browser',
              path: 'C:\\Library\\Containers\\BraveSoftware',
              size: 1400000000,
              type: 'file',
              category: 'cache',
            },
            {
              id: 'dir-cocoapods',
              name: 'CocoaPods Pods',
              path: 'C:\\Library\\Containers\\CocoaPods',
              size: 1100000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-yarn-v6',
              name: 'Yarn v6',
              path: 'C:\\Library\\Containers\\Yarn',
              size: 850000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-electron-cache',
              name: 'electron',
              path: 'C:\\Library\\Containers\\electron',
              size: 720000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-typescript-cache',
              name: 'typescript',
              path: 'C:\\Library\\Containers\\typescript',
              size: 580000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-fellow-cache',
              name: 'fellow-u...',
              path: 'C:\\Library\\Containers\\fellow',
              size: 420000000,
              type: 'file',
              category: 'other',
            },
          ],
        },
        {
          id: 'dir-docker',
          name: 'com.docker.docker Data',
          path: 'C:\\Library\\Docker',
          size: 6200000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'dir-slack',
          name: 'com.tinyspeck.slackmacg... Data',
          path: 'C:\\Library\\Slack',
          size: 3400000000,
          type: 'file',
          category: 'other',
        },
        {
          id: 'dir-app-support-group',
          name: 'Application Support',
          path: 'C:\\Library\\Application Support',
          size: 7800000000,
          type: 'directory',
          category: 'system',
          children: [
            {
              id: 'file-chrome-support',
              name: 'Google Chrome Profile ...',
              path: 'C:\\Library\\Application Support\\Google Chrome',
              size: 2800000000,
              type: 'file',
              category: 'cache',
            },
            {
              id: 'file-postman-part',
              name: 'Postman Partition...',
              path: 'C:\\Library\\Application Support\\Postman',
              size: 1900000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'file-brave-support',
              name: 'BraveSoftware Brave...',
              path: 'C:\\Library\\Application Support\\Brave',
              size: 1600000000,
              type: 'file',
              category: 'cache',
            },
            {
              id: 'file-code-user',
              name: 'Code User',
              path: 'C:\\Library\\Application Support\\Code User',
              size: 1500000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'file-vscode-extensions',
              name: '.vscode Extensions',
              path: 'C:\\Users\\User\\.vscode\\extensions',
              size: 1600000000,
              type: 'file',
              category: 'code',
            },
          ],
        },
        {
          id: 'dir-android-sdk',
          name: 'Android sdk ndk',
          path: 'C:\\Library\\Android',
          size: 6600000000,
          type: 'directory',
          category: 'code',
          children: [
            {
              id: 'file-ndk-26',
              name: '26.1.10909125 toolchains',
              path: 'C:\\Library\\Android\\26.1',
              size: 3050000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'file-ndk-27',
              name: '27.1.12297006 toolchains',
              path: 'C:\\Library\\Android\\27.1',
              size: 2450000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'file-android-build',
              name: 'build-...',
              path: 'C:\\Library\\Android\\build',
              size: 1100000000,
              type: 'file',
              category: 'code',
            },
          ],
        },
      ],
    },

    // 2. Application Cache & Assets (Center Top)
    {
      id: 'dir-app-cache',
      name: 'Application Cache & Data',
      path: 'C:\\ProgramData\\ApplicationData\\Cache',
      size: 29500000000,
      type: 'directory',
      category: 'cache',
      children: [
        {
          id: 'file-cache-chunk-1',
          name: 'asset_bundle_01.dat',
          path: 'C:\\ProgramData\\ApplicationData\\Cache\\asset_bundle_01.dat',
          size: 7370000000,
          type: 'file',
          category: 'cache',
        },
        {
          id: 'file-cache-chunk-2',
          name: 'asset_bundle_02.dat',
          path: 'C:\\ProgramData\\ApplicationData\\Cache\\asset_bundle_02.dat',
          size: 6070000000,
          type: 'file',
          category: 'cache',
        },
        {
          id: 'file-runtime-installer',
          name: 'runtime-installer.msi',
          path: 'C:\\ProgramData\\ApplicationData\\Cache\\runtime-installer.msi',
          size: 4680000000,
          type: 'file',
          category: 'system',
        },
        {
          id: 'file-shared-symbols',
          name: 'symbols_database.db',
          path: 'C:\\ProgramData\\ApplicationData\\Cache\\symbols_database.db',
          size: 3200000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-cache-chunk-3',
          name: 'asset_bundle_03.dat',
          path: 'C:\\ProgramData\\ApplicationData\\Cache\\asset_bundle_03.dat',
          size: 2020000000,
          type: 'file',
          category: 'cache',
        },
        {
          id: 'file-cache-chunk-4',
          name: 'asset_bundle_04.dat',
          path: 'C:\\ProgramData\\ApplicationData\\Cache\\asset_bundle_04.dat',
          size: 4660000000,
          type: 'file',
          category: 'cache',
        },
      ],
    },

    // 3. .gradle caches (Top Right - Bright Amber/Orange)
    {
      id: 'dir-gradle',
      name: '.gradle caches 8.10.2',
      path: 'C:\\Users\\User\\.gradle\\caches\\8.10.2',
      size: 19800000000,
      type: 'directory',
      category: 'archive',
      children: [
        {
          id: 'file-transforms-1',
          name: 'transforms ... and 135... 1.25 GB',
          path: 'C:\\Users\\User\\.gradle\\caches\\transforms-1',
          size: 1250000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-37f',
          name: '37f9861... transform...',
          path: 'C:\\Users\\User\\.gradle\\caches\\37f',
          size: 1100000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-380',
          name: '380020b... transform...',
          path: 'C:\\Users\\User\\.gradle\\caches\\380',
          size: 1050000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-0f8',
          name: '0f839437195... transforme...',
          path: 'C:\\Users\\User\\.gradle\\caches\\0f8',
          size: 980000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-1d4',
          name: '1d43ed6f... transforme...',
          path: 'C:\\Users\\User\\.gradle\\caches\\1d4',
          size: 920000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-cba',
          name: 'cbae6f... transf...',
          path: 'C:\\Users\\User\\.gradle\\caches\\cba',
          size: 890000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-814',
          name: '8.14.3 transforms ... and 762...',
          path: 'C:\\Users\\User\\.gradle\\caches\\814',
          size: 1450000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-modules-2',
          name: 'modules-2 files-2.1 com.fac...',
          path: 'C:\\Users\\User\\.gradle\\caches\\modules-2',
          size: 1600000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-wrapper-dists',
          name: 'wrapper dists',
          path: 'C:\\Users\\User\\.gradle\\caches\\wrapper',
          size: 980000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-daemon',
          name: 'daemon 6.8.3',
          path: 'C:\\Users\\User\\.gradle\\caches\\daemon',
          size: 850000000,
          type: 'file',
          category: 'archive',
        },
      ],
    },

    // 4. Media & Project Cache (Center Middle)
    {
      id: 'dir-media-cache',
      name: 'Media Render Cache',
      path: 'C:\\Users\\User\\Videos\\RenderCache',
      size: 14200000000,
      type: 'directory',
      category: 'video',
      children: [
        {
          id: 'file-render-4k',
          name: 'render_sequence_4k.raw',
          path: 'C:\\Users\\User\\Videos\\RenderCache\\render_sequence_4k.raw',
          size: 7800000000,
          type: 'file',
          category: 'video',
        },
        {
          id: 'file-render-1080p',
          name: 'proxy_preview_1080p.mp4',
          path: 'C:\\Users\\User\\Videos\\RenderCache\\proxy_preview_1080p.mp4',
          size: 6400000000,
          type: 'file',
          category: 'video',
        },
      ],
    },

    // 5. Desktop (Bottom Left/Center)
    {
      id: 'dir-desktop',
      name: 'Desktop',
      path: 'C:\\Users\\User\\Desktop',
      size: 8200000000,
      type: 'directory',
      category: 'document',
      children: [
        {
          id: 'file-presentation-video',
          name: 'Quarterly_Presentation.mp4',
          path: 'C:\\Users\\User\\Desktop\\Quarterly_Presentation.mp4',
          size: 2850000000,
          type: 'file',
          category: 'video',
        },
        {
          id: 'file-design-assets',
          name: 'Design_Assets_Archive.zip',
          path: 'C:\\Users\\User\\Desktop\\Design_Assets_Archive.zip',
          size: 2450000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-project-build',
          name: 'app_production_bundle.tar',
          path: 'C:\\Users\\User\\Desktop\\app_production_bundle.tar',
          size: 1520000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-workflow-recording',
          name: 'Tutorial_Recording.mp4',
          path: 'C:\\Users\\User\\Desktop\\Tutorial_Recording.mp4',
          size: 1380000000,
          type: 'file',
          category: 'video',
        },
      ],
    },

    // 6. Downloads & Documents (Bottom Right)
    {
      id: 'dir-downloads',
      name: 'Downloads',
      path: 'C:\\Users\\User\\Downloads',
      size: 6800000000,
      type: 'directory',
      category: 'other',
      children: [
        {
          id: 'file-l-dashboard',
          name: 'L-Dashboar...',
          path: 'C:\\Users\\User\\Downloads\\L-Dashboar...',
          size: 1450000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-dissect-mac-dmg',
          name: 'DissectMac.dmg',
          path: 'C:\\Users\\User\\Downloads\\DissectMac.dmg',
          size: 1250000000,
          type: 'file',
          category: 'system',
        },
        {
          id: 'file-jaat-web',
          name: 'JaatWeb',
          path: 'C:\\Users\\User\\Downloads\\JaatWeb',
          size: 950000000,
          type: 'file',
          category: 'code',
        },
      ],
    },
    {
      id: 'dir-documents',
      name: 'Documents',
      path: 'C:\\Users\\User\\Documents',
      size: 5200000000,
      type: 'directory',
      category: 'document',
      children: [
        {
          id: 'file-dating-w',
          name: 'dating-w... CityGem',
          path: 'C:\\Users\\User\\Documents\\dating-w',
          size: 1650000000,
          type: 'file',
          category: 'document',
        },
        {
          id: 'file-citygems',
          name: 'citygems... Pg Assis...',
          path: 'C:\\Users\\User\\Documents\\citygems',
          size: 1250000000,
          type: 'file',
          category: 'code',
        },
      ],
    },

    // 7. Developer, Cache & Media tiles (Bottom Edge)
    {
      id: 'dir-gemini',
      name: '.gemini antigravi... Default Cache',
      path: 'C:\\Users\\User\\.gemini',
      size: 2200000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-npm-cache',
      name: 'npm _cacache content-v2 _npx',
      path: 'C:\\Users\\User\\AppData\\Local\\npm-cache',
      size: 2100000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-docker-scout',
      name: '.docker scout',
      path: 'C:\\Users\\User\\.docker',
      size: 1400000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-movies',
      name: 'Movies iMovie...',
      path: 'C:\\Users\\User\\Videos',
      size: 1800000000,
      type: 'file',
      category: 'video',
    },
    {
      id: 'dir-bun-yarn',
      name: '.bun install .yarn .tabnine',
      path: 'C:\\Users\\User\\.bun',
      size: 1250000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-expo',
      name: '.expo ios-simulator-a... android...',
      path: 'C:\\Users\\User\\.expo',
      size: 1100000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-recycle-bin',
      name: 'Trash ($Recycle.Bin)',
      path: 'C:\\$Recycle.Bin',
      size: 3200000000,
      type: 'directory',
      category: 'other',
      children: [
        {
          id: 'file-trash-archive',
          name: 'OldProjectArchive.zip',
          path: 'C:\\$Recycle.Bin\\OldProjectArchive.zip',
          size: 1800000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-trash-video',
          name: 'RawRecording_4k.mp4',
          path: 'C:\\$Recycle.Bin\\RawRecording_4k.mp4',
          size: 1400000000,
          type: 'file',
          category: 'video',
        },
      ],
    },
  ],
}
