import type { FileNode } from '@shared/types'

export const DEMO_ROOT_NODE: FileNode = {
  id: 'root-c',
  name: 'Local Disk (C:)',
  path: 'C:\\',
  size: 136200000000, // ~126.84 GB
  type: 'directory',
  category: 'other',
  children: [
    // 1. Library Container (Top Left)
    {
      id: 'dir-library',
      name: 'Library',
      path: 'C:\\Library',
      size: 48500000000,
      type: 'directory',
      category: 'system',
      children: [
        {
          id: 'dir-containers',
          name: 'Containers',
          path: 'C:\\Library\\Containers',
          size: 24500000000,
          type: 'directory',
          category: 'cache',
          children: [
            {
              id: 'dir-windows-system-analysis',
              name: 'Windows.System.Analysis Data',
              path: 'C:\\Library\\Containers\\Windows.System.Analysis Data',
              size: 11850000000,
              type: 'directory',
              category: 'cache',
              children: [
                {
                  id: 'file-lib-caches',
                  name: 'Library Caches',
                  path: 'C:\\Library\\Containers\\Windows.System.Analysis Data\\Caches',
                  size: 11850000000,
                  type: 'file',
                  category: 'cache',
                },
              ],
            },
            {
              id: 'dir-unzip-any-file',
              name: 'com.Ababe.UnzipAnyFile Data',
              path: 'C:\\Library\\Containers\\com.Ababe.UnzipAnyFile Data',
              size: 9110000000,
              type: 'directory',
              category: 'cache',
              children: [
                {
                  id: 'file-app-support',
                  name: 'Library Application Support',
                  path: 'C:\\Library\\Containers\\com.Ababe.UnzipAnyFile Data\\Application Support',
                  size: 9110000000,
                  type: 'file',
                  category: 'system',
                },
              ],
            },
            {
              id: 'dir-caches-chrome',
              name: 'Caches Google Chrome',
              path: 'C:\\Library\\Containers\\Google Chrome',
              size: 3540000000,
              type: 'directory',
              category: 'cache',
              children: [
                {
                  id: 'file-prof-5',
                  name: 'Profile 5 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 5',
                  size: 889090000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-8',
                  name: 'Profile 8 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 8',
                  size: 836760000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-10',
                  name: 'Profile 10 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 10',
                  size: 793660000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-1',
                  name: 'Profile 1 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 1',
                  size: 420000000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-prof-11',
                  name: 'Profile 11 Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Profile 11',
                  size: 320000000,
                  type: 'file',
                  category: 'cache',
                },
                {
                  id: 'file-code-cache',
                  name: 'Code Cache',
                  path: 'C:\\Library\\Containers\\Google Chrome\\Code Cache',
                  size: 280490000,
                  type: 'file',
                  category: 'code',
                },
              ],
            },
            {
              id: 'dir-brave',
              name: 'BraveSoftware Brave-Browser',
              path: 'C:\\Library\\Containers\\BraveSoftware',
              size: 1400000000,
              type: 'file',
              category: 'cache',
            },
            {
              id: 'dir-cocoapods',
              name: 'CocoaPods Pods',
              path: 'C:\\Library\\Containers\\CocoaPods',
              size: 1100000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-yarn-v6',
              name: 'Yarn v6',
              path: 'C:\\Library\\Containers\\Yarn',
              size: 850000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-electron-cache',
              name: 'electron',
              path: 'C:\\Library\\Containers\\electron',
              size: 720000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-typescript-cache',
              name: 'typescript',
              path: 'C:\\Library\\Containers\\typescript',
              size: 580000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'dir-fellow-cache',
              name: 'fellow-u...',
              path: 'C:\\Library\\Containers\\fellow',
              size: 420000000,
              type: 'file',
              category: 'other',
            },
          ],
        },
        {
          id: 'dir-docker',
          name: 'com.docker.docker Data',
          path: 'C:\\Library\\Docker',
          size: 6200000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'dir-slack',
          name: 'com.tinyspeck.slackmacg... Data',
          path: 'C:\\Library\\Slack',
          size: 3400000000,
          type: 'file',
          category: 'other',
        },
        {
          id: 'dir-app-support-group',
          name: 'Application Support',
          path: 'C:\\Library\\Application Support',
          size: 7800000000,
          type: 'directory',
          category: 'system',
          children: [
            {
              id: 'file-chrome-support',
              name: 'Google Chrome Profile ...',
              path: 'C:\\Library\\Application Support\\Google Chrome',
              size: 2800000000,
              type: 'file',
              category: 'cache',
            },
            {
              id: 'file-postman-part',
              name: 'Postman Partition...',
              path: 'C:\\Library\\Application Support\\Postman',
              size: 1900000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'file-brave-support',
              name: 'BraveSoftware Brave...',
              path: 'C:\\Library\\Application Support\\Brave',
              size: 1600000000,
              type: 'file',
              category: 'cache',
            },
            {
              id: 'file-code-user',
              name: 'Code User',
              path: 'C:\\Library\\Application Support\\Code User',
              size: 1500000000,
              type: 'file',
              category: 'code',
            },
          ],
        },
        {
          id: 'dir-android-sdk',
          name: 'Android sdk ndk',
          path: 'C:\\Library\\Android',
          size: 6600000000,
          type: 'directory',
          category: 'code',
          children: [
            {
              id: 'file-ndk-26',
              name: '26.1.10909125 toolchains',
              path: 'C:\\Library\\Android\\26.1',
              size: 3050000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'file-ndk-27',
              name: '27.1.12297006 toolchains',
              path: 'C:\\Library\\Android\\27.1',
              size: 2450000000,
              type: 'file',
              category: 'code',
            },
            {
              id: 'file-android-build',
              name: 'build-...',
              path: 'C:\\Library\\Android\\build',
              size: 1100000000,
              type: 'file',
              category: 'code',
            },
          ],
        },
      ],
    },

    // 2. .ollama models blobs (Center Top)
    {
      id: 'dir-ollama',
      name: '.ollama models blobs',
      path: 'C:\\Users\\User\\.ollama\\models\\blobs',
      size: 29500000000,
      type: 'directory',
      category: 'code',
      children: [
        {
          id: 'file-sha-780e',
          name: 'sha256-780e28c2943069a5a384afe0a5b5a667de8...',
          path: 'C:\\Users\\User\\.ollama\\models\\blobs\\sha256-780e',
          size: 7370000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-sha-416e',
          name: 'sha256-416e45a35835249480f30c83378473b5184...',
          path: 'C:\\Users\\User\\.ollama\\models\\blobs\\sha256-416e',
          size: 6070000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-fernum-setup',
          name: 'Fernum-Setup.exe',
          path: 'C:\\Users\\User\\.ollama\\models\\blobs\\Fernum-Setup.exe',
          size: 4680000000,
          type: 'file',
          category: 'system',
        },
        {
          id: 'file-fernum-online',
          name: 'fernum.online storage analyzer',
          path: 'C:\\Users\\User\\.ollama\\models\\blobs\\fernum.online',
          size: 3200000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-sha-dde5',
          name: 'sha256-dde5aa3fc5ffc1...',
          path: 'C:\\Users\\User\\.ollama\\models\\blobs\\sha256-dde5',
          size: 2020000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-sha-ea02',
          name: 'sha256-ea025c107c1c3e...',
          path: 'C:\\Users\\User\\.ollama\\models\\blobs\\sha256-ea02',
          size: 4660000000,
          type: 'file',
          category: 'code',
        },
      ],
    },

    // 3. .gradle caches (Top Right - Bright Amber/Orange)
    {
      id: 'dir-gradle',
      name: '.gradle caches 8.10.2',
      path: 'C:\\Users\\User\\.gradle\\caches\\8.10.2',
      size: 19800000000,
      type: 'directory',
      category: 'archive',
      children: [
        {
          id: 'file-transforms-1',
          name: 'transforms ... and 135... 1.25 GB',
          path: 'C:\\Users\\User\\.gradle\\caches\\transforms-1',
          size: 1250000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-37f',
          name: '37f9861... transform...',
          path: 'C:\\Users\\User\\.gradle\\caches\\37f',
          size: 1100000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-380',
          name: '380020b... transform...',
          path: 'C:\\Users\\User\\.gradle\\caches\\380',
          size: 1050000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-0f8',
          name: '0f839437195... transforme...',
          path: 'C:\\Users\\User\\.gradle\\caches\\0f8',
          size: 980000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-1d4',
          name: '1d43ed6f... transforme...',
          path: 'C:\\Users\\User\\.gradle\\caches\\1d4',
          size: 920000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-cba',
          name: 'cbae6f... transf...',
          path: 'C:\\Users\\User\\.gradle\\caches\\cba',
          size: 890000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-transforms-814',
          name: '8.14.3 transforms ... and 762...',
          path: 'C:\\Users\\User\\.gradle\\caches\\814',
          size: 1450000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-modules-2',
          name: 'modules-2 files-2.1 com.fac...',
          path: 'C:\\Users\\User\\.gradle\\caches\\modules-2',
          size: 1600000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-wrapper-dists',
          name: 'wrapper dists',
          path: 'C:\\Users\\User\\.gradle\\caches\\wrapper',
          size: 980000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-daemon',
          name: 'daemon 6.8.3',
          path: 'C:\\Users\\User\\.gradle\\caches\\daemon',
          size: 850000000,
          type: 'file',
          category: 'archive',
        },
      ],
    },

    // 4. .cache lm-studio models (Center Middle)
    {
      id: 'dir-lmstudio',
      name: '.cache lm-studio models',
      path: 'C:\\Users\\User\\.cache\\lm-studio\\models',
      size: 14200000000,
      type: 'directory',
      category: 'code',
      children: [
        {
          id: 'file-orenguteng',
          name: 'Orenguteng Llama-3.1-8B-Lexi-Uncensored... 4.66 GB',
          path: 'C:\\Users\\User\\.cache\\lm-studio\\models\\Orenguteng',
          size: 4660000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-gemma',
          name: 'lmstudio-co... gemma-2-2b... 1.71 GB',
          path: 'C:\\Users\\User\\.cache\\lm-studio\\models\\gemma',
          size: 1710000000,
          type: 'file',
          category: 'code',
        },
      ],
    },

    // 5. Desktop (Bottom Left/Center)
    {
      id: 'dir-desktop',
      name: 'Desktop',
      path: 'C:\\Users\\User\\Desktop',
      size: 8200000000,
      type: 'directory',
      category: 'document',
      children: [
        {
          id: 'file-mac-storage-vis',
          name: 'mac storage visual...',
          path: 'C:\\Users\\User\\Desktop\\mac storage visual...',
          size: 1850000000,
          type: 'file',
          category: 'video',
        },
        {
          id: 'file-heaven-marr',
          name: 'Heaven marr... smile...',
          path: 'C:\\Users\\User\\Desktop\\Heaven marr...',
          size: 1450000000,
          type: 'file',
          category: 'image',
        },
        {
          id: 'file-dist',
          name: 'dist node_m...',
          path: 'C:\\Users\\User\\Desktop\\dist',
          size: 1100000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-screen-reco',
          name: 'Screen Reco...',
          path: 'C:\\Users\\User\\Desktop\\Screen Reco...',
          size: 980000000,
          type: 'file',
          category: 'video',
        },
        {
          id: 'file-dissectmac-com',
          name: 'dissectmac.com',
          path: 'C:\\Users\\User\\Desktop\\dissectmac.com',
          size: 820000000,
          type: 'file',
          category: 'code',
        },
        {
          id: 'file-dpr-dashboard',
          name: 'dpr-dashboa...',
          path: 'C:\\Users\\User\\Desktop\\dpr-dashboa...',
          size: 780000000,
          type: 'file',
          category: 'code',
        },
      ],
    },

    // 6. Downloads & Documents (Bottom Right)
    {
      id: 'dir-downloads',
      name: 'Downloads',
      path: 'C:\\Users\\User\\Downloads',
      size: 6800000000,
      type: 'directory',
      category: 'other',
      children: [
        {
          id: 'file-l-dashboard',
          name: 'L-Dashboar...',
          path: 'C:\\Users\\User\\Downloads\\L-Dashboar...',
          size: 1450000000,
          type: 'file',
          category: 'archive',
        },
        {
          id: 'file-dissect-mac-dmg',
          name: 'DissectMac.dmg',
          path: 'C:\\Users\\User\\Downloads\\DissectMac.dmg',
          size: 1250000000,
          type: 'file',
          category: 'system',
        },
        {
          id: 'file-jaat-web',
          name: 'JaatWeb',
          path: 'C:\\Users\\User\\Downloads\\JaatWeb',
          size: 950000000,
          type: 'file',
          category: 'code',
        },
      ],
    },
    {
      id: 'dir-documents',
      name: 'Documents',
      path: 'C:\\Users\\User\\Documents',
      size: 5200000000,
      type: 'directory',
      category: 'document',
      children: [
        {
          id: 'file-dating-w',
          name: 'dating-w... CityGem',
          path: 'C:\\Users\\User\\Documents\\dating-w',
          size: 1650000000,
          type: 'file',
          category: 'document',
        },
        {
          id: 'file-citygems',
          name: 'citygems... Pg Assis...',
          path: 'C:\\Users\\User\\Documents\\citygems',
          size: 1250000000,
          type: 'file',
          category: 'code',
        },
      ],
    },

    // 7. Developer, Cache & Media tiles (Bottom Edge)
    {
      id: 'dir-gemini',
      name: '.gemini antigravi... Default Cache',
      path: 'C:\\Users\\User\\.gemini',
      size: 2200000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-npm-cache',
      name: 'npm _cacache content-v2 _npx',
      path: 'C:\\Users\\User\\AppData\\Local\\npm-cache',
      size: 2100000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-docker-scout',
      name: '.docker scout',
      path: 'C:\\Users\\User\\.docker',
      size: 1400000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-movies',
      name: 'Movies iMovie...',
      path: 'C:\\Users\\User\\Videos',
      size: 1800000000,
      type: 'file',
      category: 'video',
    },
    {
      id: 'dir-bun-yarn',
      name: '.bun install .yarn .tabnine',
      path: 'C:\\Users\\User\\.bun',
      size: 1250000000,
      type: 'file',
      category: 'code',
    },
    {
      id: 'dir-expo',
      name: '.expo ios-simulator-a... android...',
      path: 'C:\\Users\\User\\.expo',
      size: 1100000000,
      type: 'file',
      category: 'code',
    },
  ],
}
